### ISSUE TITLE
Push tag to GitHub?

### ISSUE THREAD

**Issue by jas4711** [openwall/tcb#19]
Hi.  I am considering packaging tcb for Debian.  Would you mind pushing the 1.2 release tag to GitHub?  That makes it a bit easier to extract the relevant files, and to compare with the tarball.

https://bugs.debian.org/1083207

Thanks,
Simon

**Comment by solardiz** [comment]
Hi @jas4711. I've just tagged 1.2 and pushed the tag to GitHub. Thank you!
